### ISSUE TITLE
Get Recently viewed products

### ISSUE THREAD

**Issue by aganglada** [bigcommerce/storefront-data-hooks#59]
Notice inside the Account Page, there is a section called "Recently Viewed" where recently viewed products show.

<img width="1023" alt="Screenshot 2021-04-13 at 14 44 30" src="https://user-images.githubusercontent.com/922348/114554458-a68c3f00-9c5e-11eb-89b2-eaf263d7ac20.png">

Is there a way to get those products from a `graphql` endpoint or other method? If so, maybe is a good fit for this package to be added as a feature. 

WDYT?

**Comment by jorgemasta** [comment]
I have not found any way to get that data from the API (neither graphql nor rest) either.

Technically for a headless store it seems very complex since in order to obtain that data we first have to have communicated to the backend that we have visited those products. And **maybe** this should not be the responsibility of the BC API, but of another service.

I am closing this ticket until we have some news.

**Comment by aganglada** [comment]
Thank you @jorgemasta!

**Comment by kogan007** [comment]
@jorgemasta @aganglada 

I did this on my project using localstorage and useeffect (NextJS). 
Just push every product you visit into the storage and filter out the product you're currently looking at from that list.
